# Generated by Django 6.0 on 2026-01-01 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_finansalhareket_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaasBordrosu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donem', models.DateField(verbose_name="Dönem (Her ayın 1'i)")),
                ('brut_maas', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='O Ayki Maaş/Yevmiye')),
                ('calistigi_gun', models.IntegerField(default=0, verbose_name='Çalıştığı Gün')),
                ('gelmedigi_gun', models.IntegerField(default=0, verbose_name='Gelmediği Gün')),
                ('mesai_saati', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Mesai Saati')),
                ('mesai_ucreti', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mesai Ücreti')),
                ('toplam_prim', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Toplam Prim')),
                ('toplam_kesinti', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Toplam Kesinti')),
                ('net_odenecek', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net Ödenecek Tutar')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='İşlem Tarihi')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.personel', verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Maaş Bordrosu (Kesinleşmiş)',
                'verbose_name_plural': 'Maaş Bordroları',
                'unique_together': {('personel', 'donem')},
            },
        ),
    ]
