# Generated by Django 6.0 on 2026-01-01 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_maasbordrosu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IslemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_turu', models.CharField(choices=[('ekleme', 'Ekleme'), ('guncelleme', 'Güncelleme'), ('silme', 'Silme'), ('kritik', 'Kritik İşlem (Bordro vb.)')], max_length=20, verbose_name='İşlem Türü')),
                ('konu', models.CharField(max_length=100, verbose_name='Konu (Örn: Finansal Hareket)')),
                ('detay', models.TextField(verbose_name='İşlem Detayı')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Tarih/Saat')),
                ('ilgili_personel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.personel', verbose_name='İlgili Personel')),
                ('kullanici', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
            ],
            options={
                'verbose_name': 'İşlem Logu',
                'verbose_name_plural': 'İşlem Logları (Audit)',
                'ordering': ['-tarih'],
            },
        ),
    ]
